use std::env;
use std::fs;
use std::path::Path;

#[path = "src/source_taxonomy.rs"]
mod source_taxonomy;

use source_taxonomy::{parse_opencpn_chart_sources, OpenCPNChartSourceRecord};

const OPENCPN_SOURCES_XML: &str = include_str!("data/opencpn_enc_sources.xml");

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let xml_path = Path::new(&manifest_dir).join("data/opencpn_enc_sources.xml");
    println!("cargo:rerun-if-changed={}", xml_path.display());
    println!("cargo:rerun-if-changed=src/source_taxonomy.rs");

    let sources = parse_opencpn_chart_sources(OPENCPN_SOURCES_XML)
        .expect("parse embedded OpenCPN sources XML");
    assert!(
        !sources.is_empty(),
        "opencpn_enc_sources.xml must define at least one chart source"
    );

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let out_path = Path::new(&out_dir).join("sources_generated.rs");
    fs::write(&out_path, generate_rust(sources.len(), &sources))
        .expect("write sources_generated.rs");
}

fn generate_rust(source_count: usize, sources: &[OpenCPNChartSourceRecord]) -> String {
    let mut out = String::from("// @generated by build.rs — do not edit\n\n");
    out.push_str(&format!(
        "pub(super) const EMBEDDED_SOURCE_COUNT: usize = {source_count};\n\n"
    ));
    out.push_str("pub(super) static EMBEDDED_SOURCES: &[ChartSource] = &[\n");
    for source in sources {
        out.push_str("    ChartSource {\n");
        out.push_str(&format!("        name: {:?},\n", source.name));
        out.push_str(&format!("        catalog_url: {:?},\n", source.catalog_url));
        out.push_str(&format!(
            "        catalog_filename: {:?},\n",
            source.catalog_filename
        ));
        out.push_str(&format!("        folder: {:?},\n", source.folder));
        out.push_str("    },\n");
    }
    out.push_str("];\n");
    out.push_str("const _: () = assert!(EMBEDDED_SOURCES.len() == EMBEDDED_SOURCE_COUNT);\n");
    out
}
