name: finalize-release-artifacts

on:
  workflow_call:
    inputs:
      release_version:
        required: true
        type: string

jobs:
  finalize-release-artifacts:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Download build artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: artifacts-*
          path: target/distrib/
          merge-multiple: true

      - name: Prepare release bundle
        env:
          RELEASE_VERSION: ${{ inputs.release_version }}
        run: ./scripts/prepare-release-bundle.sh

      - name: Upload release bundle
        uses: actions/upload-artifact@v7
        with:
          name: enc-sync-${{ inputs.release_version }}
          path: release-staging/
